# 路径1：我的工作台-运维管理综合查询-[工单类型：历史工单，故障来源：移动/联通/电信运营商接口+铁塔集团接口，受理/回单起/始时间]-查询-导出-列表及详情
self.now = datetime.datetime.now().replace(hour=0, minute=0, second=0) - datetime.timedelta(days=day)
self.start = self.now - datetime.timedelta(days=1)

INTO_DATA1 = {'AJAXREQUEST': '_viewRoot',
              'javax.faces.ViewState': 'j_id8',
              'queryForm': 'queryForm',
              'queryForm:addOrEditAreaNameId': '',
              'queryForm:aid': '',
              'queryForm:alarmlevel_hiddenValue': '',
              'queryForm:billStatus_hiddenValue': '',
              'queryForm:btn': 'queryForm:btn',
              'queryForm:dealendtimeInputCurrentDate': self.now.strftime('%m/%Y'),
              'queryForm:dealendtimeInputDate': '',
              'queryForm:dealstarttimeInputCurrentDate': self.now.strftime('%m/%Y'),
              'queryForm:dealstarttimeInputDate': '',
              'queryForm:deletecityIdHidden': '',
              'queryForm:deletecountryIdHidden': '',
              'queryForm:deleteproviceIdHidden': '',
              'queryForm:deviceidText': '',
              'queryForm:endtimeInputCurrentDate': self.now.strftime('%m/%Y'),
              'queryForm:endtimeInputDate': self.now.strftime('%Y-%m-%d %H:%M'),
              'queryForm:faultDevType_hiddenValue': '',
              'queryForm:faultSrc': '铁塔集团动环网管',
              'queryForm:faultSrc_hiddenValue': '铁塔集团动环网管,移动运营商接口,联通运营商接口,电信运营商接口',
              'queryForm:faultTypeId_hiddenValue': '',
              'queryForm:hideFlag': '',
              'queryForm:isHasten_hiddenValue': '',
              'queryForm:isOverTime_hiddenValue': '',
              'queryForm:isQueryHis': 'W',
              'queryForm:isReplyOver_hiddenValue': '',
              'queryForm:isTransitNodeId_hiddenValue': '',
              'queryForm:isTurnBack_hiddenValue': '',
              'queryForm:j_id139': '',
              'queryForm:j_id143': '',
              'queryForm:j_id48': '',
              'queryForm:j_id58': '',
              'queryForm:msg': '0',
              'queryForm:operatorLevel_hiddenValue': '',
              'queryForm:panelOpenedState': '',
              'queryForm:queryAlarmId': '',
              'queryForm:queryAlarmName': '',
              'queryForm:queryBillId': '',
              'queryForm:queryBillSn': '',
              'queryForm:queryCrewAreaId': '',
              'queryForm:queryCrewCityId': '',
              'queryForm:queryCrewProvinceId': '',
              'queryForm:queryCrewVillageId': '',
              'queryForm:queryCrewVillageName': '',
              'queryForm:queryDWCompany': '',
              'queryForm:queryDWCompanyName': '',
              'queryForm:queryDeleteCountyName': '',
              'queryForm:queryStationId': '',
              'queryForm:queryUnitId': '0099977',
              'queryForm:querystationstatus_hiddenValue': '',
              'queryForm:refreshTime': '',
              'queryForm:revertendtimeInputCurrentDate': self.now.strftime('%m/%Y'),
              'queryForm:revertendtimeInputDate': self.now.strftime('%Y-%m-%d %H:%M'),
              'queryForm:revertstarttimeInputCurrentDate': self.start.strftime('%m/%Y'),
              'queryForm:revertstarttimeInputDate': self.start.strftime('%Y-%m-%d %H:%M'),
              'queryForm:sitesource_hiddenValue': '',
              'queryForm:sortSelect_hiddenValue': '',
              'queryForm:starttimeInputCurrentDate': self.start.strftime('%m/%Y'),
              'queryForm:starttimeInputDate': self.start.strftime('%Y-%m-%d %H:%M'),
              'queryForm:subOperatorHid_hiddenValue': '',
              'queryForm:turnSend_hiddenValue': ''}

INTO_DATA2 = {'AJAX:EVENTS_COUNT': '1',
              'AJAXREQUEST': '_viewRoot',
              'javax.faces.ViewState': 'j_id8',
              'queryForm': 'queryForm',
              'queryForm:addOrEditAreaNameId': '',
              'queryForm:aid': '',
              'queryForm:alarmlevel_hiddenValue': '',
              'queryForm:billStatus_hiddenValue': '',
              'queryForm:dealendtimeInputCurrentDate': self.now.strftime('%m/%Y'),
              'queryForm:dealendtimeInputDate': '',
              'queryForm:dealstarttimeInputCurrentDate': self.now.strftime('%m/%Y'),
              'queryForm:dealstarttimeInputDate': '',
              'queryForm:deletecityIdHidden': '',
              'queryForm:deletecountryIdHidden': '',
              'queryForm:deleteproviceIdHidden': '',
              'queryForm:deviceidText': '',
              'queryForm:endtimeInputCurrentDate': self.now.strftime('%m/%Y'),
              'queryForm:endtimeInputDate': self.now.strftime('%Y-%m-%d %H:%M'),
              'queryForm:faultDevType_hiddenValue': '',
              'queryForm:faultSrc': '铁塔集团动环网管',
              'queryForm:faultSrc_hiddenValue': '铁塔集团动环网管,移动运营商接口,联通运营商接口,电信运营商接口',
              'queryForm:faultTypeId_hiddenValue': '',
              'queryForm:hideFlag': '',
              'queryForm:isHasten_hiddenValue': '',
              'queryForm:isOverTime_hiddenValue': '',
              'queryForm:isQueryHis': 'W',
              'queryForm:isReplyOver_hiddenValue': '',
              'queryForm:isTransitNodeId_hiddenValue': '',
              'queryForm:isTurnBack_hiddenValue': '',
              'queryForm:j_id139': '',
              'queryForm:j_id143': '',
              'queryForm:j_id150': 'queryForm:j_id150',
              'queryForm:j_id48': '',
              'queryForm:j_id58': '',
              'queryForm:msg': '0',
              'queryForm:operatorLevel_hiddenValue': '',
              'queryForm:panelOpenedState': '',
              'queryForm:queryAlarmId': '',
              'queryForm:queryAlarmName': '',
              'queryForm:queryBillId': '',
              'queryForm:queryBillSn': '',
              'queryForm:queryCrewAreaId': '',
              'queryForm:queryCrewCityId': '',
              'queryForm:queryCrewProvinceId': '',
              'queryForm:queryCrewVillageId': '',
              'queryForm:queryCrewVillageName': '',
              'queryForm:queryDWCompany': '',
              'queryForm:queryDWCompanyName': '',
              'queryForm:queryDeleteCountyName': '',
              'queryForm:queryStationId': '',
              'queryForm:queryUnitId': '0099977',
              'queryForm:querystationstatus_hiddenValue': '',
              'queryForm:refreshTime': '',
              'queryForm:revertendtimeInputCurrentDate': self.now.strftime('%m/%Y'),
              'queryForm:revertendtimeInputDate': self.now.strftime('%Y-%m-%d %H:%M'),
              'queryForm:revertstarttimeInputCurrentDate': self.start.strftime('%m/%Y'),
              'queryForm:revertstarttimeInputDate': self.start.strftime('%Y-%m-%d %H:%M'),
              'queryForm:sitesource_hiddenValue': '',
              'queryForm:sortSelect_hiddenValue': '',
              'queryForm:starttimeInputCurrentDate': self.start.strftime('%m/%Y'),
              'queryForm:starttimeInputDate': self.start.strftime('%Y-%m-%d %H:%M'),
              'queryForm:subOperatorHid_hiddenValue': '',
              'queryForm:turnSend_hiddenValue': ''}
INTO_DATA_FINAL = {'j_id1945': 'j_id1945',
                   'j_id1945:devExport': '全部',
                   'j_id1945:j_id1947': 'Y',
                   'javax.faces.ViewState': 'j_id8'}